-- =========================================================
-- Procedure: SP_LOAN_AMORTIZATION_SCHEDULE
-- Purpose:
-- Generate loan repayment schedules and amortization
-- cashflow projections for lending analytics
--
-- Features:
-- - Outstanding balance tracking
-- - Principal repayment calculation
-- - Interest accrual calculation
-- - Installment cashflow generation
--
-- Author: Trang Thai
-- =========================================================

CREATE PROC PRC_TRANGTH_BAOCAO_TINDUNG_2024
    @year INT -- Năm cần lọc
AS
BEGIN
    -- Bảng lưu kết quả báo cáo
    DECLARE @BAOCAO TABLE (
        TIEUCHI NVARCHAR(255),           -- Tiêu chí
        SOLUONG_HDTD INT,                -- Số lượng hợp đồng tín dụng
        TILE_SOLUONG FLOAT,              -- Tỷ lệ số lượng (%)
        TONGTIEN_GIAINGAN NUMERIC(18,2), -- Tổng số tiền giải ngân
        TILE_TONGTIEN FLOAT              -- Tỷ lệ tổng số tiền (%)
    );

    -- Tổng số lượng hợp đồng và tổng tiền giải ngân theo năm
    DECLARE @TOTAL_HDTD INT, @TOTAL_TIEN NUMERIC(18,2);
    SELECT 
        @TOTAL_HDTD = ISNULL(COUNT(*), 0), 
        @TOTAL_TIEN = ISNULL(SUM(SOTIEN), 0)
    FROM HOPDONG_TINDUNG
    WHERE YEAR(NGAY_GIAINGAN) = @year;

    -- I. Tổng hợp theo mục đích cấp tín dụng
    INSERT INTO @BAOCAO
    SELECT 
        N'I. Mục đích cấp tín dụng' AS TIEUCHI,
        @TOTAL_HDTD AS SOLUONG_HDTD,
        100 AS TILE_SOLUONG,
        @TOTAL_TIEN AS TONGTIEN_GIAINGAN,
        100 AS TILE_TONGTIEN;

    -- I.1 Tín dụng bất động sản
    INSERT INTO @BAOCAO
    SELECT 
        N'I.1 Tín dụng bất động sản',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN MUCDICH_CAPTINDUNG MD ON HTD.MA_MUCDICH_CAPTD = MD.MA_MUCDICH_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND MD.MA_CAP1 = 1;

    -- I.2 Tín dụng phục vụ nhu cầu đời sống
    INSERT INTO @BAOCAO
    SELECT 
        N'I.2 Tín dụng phục vụ nhu cầu đời sống',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN MUCDICH_CAPTINDUNG MD ON HTD.MA_MUCDICH_CAPTD = MD.MA_MUCDICH_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND MD.MA_CAP1 = 2;

    -- I.3 Tín dụng đầu tư
    INSERT INTO @BAOCAO
    SELECT 
        N'I.3 Tín dụng đầu tư',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN MUCDICH_CAPTINDUNG MD ON HTD.MA_MUCDICH_CAPTD = MD.MA_MUCDICH_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND MD.MA_CAP1 = 3;

    -- II. Tổng hợp theo hình thức cấp tín dụng
    INSERT INTO @BAOCAO
    SELECT 
        N'II. Hình thức cấp tín dụng' AS TIEUCHI,
        @TOTAL_HDTD AS SOLUONG_HDTD,
        100 AS TILE_SOLUONG,
        @TOTAL_TIEN AS TONGTIEN_GIAINGAN,
        100 AS TILE_TONGTIEN;

    -- II.1 Cho vay
    INSERT INTO @BAOCAO
    SELECT 
        N'II.1 Cho vay',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN HINHTHUC_CAPTINDUNG HT ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND HT.MA_CAP1 = 1;

    -- II.2 Cho thuê tài chính
    INSERT INTO @BAOCAO
    SELECT 
        N'II.2 Cho thuê tài chính',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN HINHTHUC_CAPTINDUNG HT ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND HT.MA_CAP1 = 2;

    -- II.3 Chiết khấu
    INSERT INTO @BAOCAO
    SELECT 
        N'II.3 Chiết khấu',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN HINHTHUC_CAPTINDUNG HT ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND HT.MA_CAP1 = 3;

    -- II.4 Bao thanh toán
    INSERT INTO @BAOCAO
    SELECT 
        N'II.4 Bao thanh toán',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN HINHTHUC_CAPTINDUNG HT ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND HT.MA_CAP1 = 4;

    -- II.5 Trả thay theo cam kết ngoại bảng
    INSERT INTO @BAOCAO
    SELECT 
        N'II.5 Trả thay theo cam kết ngoại bảng',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN HINHTHUC_CAPTINDUNG HT ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND HT.MA_CAP1 = 5;

    -- II.6 Ủy thác
    INSERT INTO @BAOCAO
    SELECT 
        N'II.6 Ủy thác',
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT),2) AS TILE_SOLUONG,
        ISNULL(SUM(SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT),2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN HINHTHUC_CAPTINDUNG HT ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year AND HT.MA_CAP1 = 6;

	-- III. Tổng hợp toàn bộ ngành nghề kinh tế
	INSERT INTO @BAOCAO
	SELECT 
		N'III. Theo ngành nghề kinh tế' AS TIEUCHI,
		@TOTAL_HDTD AS SOLUONG_HDTD,
		100 AS TILE_SOLUONG,
		@TOTAL_TIEN AS TONGTIEN_GIAINGAN,
		100 AS TILE_TONGTIEN;

	-- Liên kết và tổng hợp theo từng ngành nghề
	INSERT INTO @BAOCAO
	SELECT 
		CONCAT(N'III.', NN1.MA_NGANHNGHE_KINHTE_CAP01, ' ', NN1.TEN_NGANHNGHE_KINHTE_CAP01) AS TIEUCHI,
		ISNULL(COUNT(HTD.MA_HOPDONG_TINDUNG), 0) AS SOLUONG_HDTD,
		ROUND(CAST(ISNULL(COUNT(HTD.MA_HOPDONG_TINDUNG), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT), 2) AS TILE_SOLUONG,
		ISNULL(SUM(HTD.SOTIEN), 0) AS TONGTIEN_GIAINGAN,
		ROUND(CAST(ISNULL(SUM(HTD.SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT), 2) AS TILE_TONGTIEN
	FROM NGANHNGHE_KINHTE_CAP01 NN1
	LEFT JOIN NGANHNGHE_KINHTE_CAP02 NN2 ON NN1.MA_NGANHNGHE_KINHTE_CAP01 = NN2.MA_NGANHNGHE_KINHTE_CAP01
	LEFT JOIN NGANHNGHE_KINHTE_CAP03 NN3 ON NN2.MA_NGANHNGHE_KINHTE_CAP02 = NN3.MA_NGANHNGHE_KINHTE_CAP02
	LEFT JOIN KHACHHANG KH ON NN3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
	LEFT JOIN HOPDONG_TINDUNG HTD ON KH.MA_KHACHHANG = HTD.MA_KHACHHANG AND YEAR(HTD.NGAY_GIAINGAN) = @year
	GROUP BY NN1.MA_NGANHNGHE_KINHTE_CAP01, NN1.TEN_NGANHNGHE_KINHTE_CAP01;

    -- IV. Tổng hợp toàn bộ sản phẩm tín dụng
    INSERT INTO @BAOCAO
    SELECT 
        N'IV. Theo sản phẩm tín dụng' AS TIEUCHI,
        @TOTAL_HDTD AS SOLUONG_HDTD,
        100 AS TILE_SOLUONG,
        @TOTAL_TIEN AS TONGTIEN_GIAINGAN,
        100 AS TILE_TONGTIEN;

    -- Báo cáo theo từng sản phẩm tín dụng
    INSERT INTO @BAOCAO
    SELECT 
        CONCAT(N'IV.', SP.MASP, ' ', SP.TENSP) AS TIEUCHI,
        ISNULL(COUNT(*), 0) AS SOLUONG_HDTD,
        ROUND(CAST(ISNULL(COUNT(*), 0) * 100.0 / ISNULL(@TOTAL_HDTD, 1) AS FLOAT), 2) AS TILE_SOLUONG,
        ISNULL(SUM(HTD.SOTIEN), 0) AS TONGTIEN_GIAINGAN,
        ROUND(CAST(ISNULL(SUM(HTD.SOTIEN), 0) * 100.0 / ISNULL(@TOTAL_TIEN, 1) AS FLOAT), 2) AS TILE_TONGTIEN
    FROM HOPDONG_TINDUNG HTD
    INNER JOIN SANPHAM_TINDUNG SP ON HTD.MA_SANPHAM_TD = SP.MASP
    WHERE YEAR(HTD.NGAY_GIAINGAN) = @year
    GROUP BY SP.MASP, SP.TENSP;

    -- Trả kết quả báo cáo
    SELECT * FROM @BAOCAO;
END;

--- NHẬP năm (@year) ĐƯA RA KẾT QUẢ

EXEC PRC_TRANGTH_BAOCAO_TINDUNG_2024 @year = 2024;


-----------------------------------------------------------------------------------------------------------------

CREATE VIEW v_BAOCAO_TINDUNG
AS

SELECT      
        HTD.MA_HOPDONG_TINDUNG,
        HTD.SOTIEN,
        MD.TEN_MUCDICH_CAP1,
        HT.TEN_HINHTHUC_CAP1,
        NN1.TEN_NGANHNGHE_KINHTE_CAP01,
        SP.TENSP,
        HTD.NGAY_GIAINGAN

FROM        HOPDONG_TINDUNG HTD

INNER JOIN  MUCDICH_CAPTINDUNG MD
ON HTD.MA_MUCDICH_CAPTD = MD.MA_MUCDICH_CAPTD

INNER JOIN  HINHTHUC_CAPTINDUNG HT
ON HTD.MA_HINHTHUC_CAPTD = HT.MA_HINHTHUC_CAPTD

INNER JOIN  KHACHHANG KH
ON HTD.MA_KHACHHANG = KH.MA_KHACHHANG

INNER JOIN  NGANHNGHE_KINHTE_CAP03 NN3
ON KH.MA_NGANHNGHE_KINHTE = NN3.MA_NGANHNGHE_KINHTE_CAP03

INNER JOIN  NGANHNGHE_KINHTE_CAP01 NN1
ON NN3.MA_NGANHNGHE_KINHTE_CAP01 = NN1.MA_NGANHNGHE_KINHTE_CAP01

INNER JOIN SANPHAM_TINDUNG SP
ON HTD.MA_SANPHAM_TD = SP.MASP;

SELECT *
FROM v_BAOCAO_TINDUNG
WHERE YEAR(NGAY_GIAINGAN) = 2024;

-----------------------------------------------------------------------------------------------------------------

CREATE TABLE KEHOACH
(
    [Mã HDTD] NVARCHAR(50),
    [Kỳ] INT,
    [Số dư đầu kỳ] NUMERIC(18,0),
    [Ngày đầu kỳ] DATE,
    [Ngày cuối kỳ] DATE,
    [Số ngày tính lãi] INT,
    [Lãi suất trong hạn] NUMERIC(5,2),
    [Gốc phải trả] NUMERIC(18,0),
    [Lãi phải trả] NUMERIC(18,0),
    [Tổng tiền phải trả] NUMERIC(18,0)
);
GO

IF OBJECT_ID('KEHOACH_TRANO') IS NOT NULL
DROP PROC KEHOACH_TRANO
GO

CREATE PROC KEHOACH_TRANO
@MAHDTD NVARCHAR(20)
AS
BEGIN

-- Xóa kế hoạch cũ
DELETE FROM KEHOACH
WHERE [Mã HDTD] = @MAHDTD;

DECLARE
    @KYHAN INT,
    @LAISUAT NUMERIC(5,2),
    @SOTIEN NUMERIC(18,0),
    @NGAY_GN DATE,
    @NGAY_DH DATE,
    @I INT = 1,
    @GOCPHAITRA_MOIKY NUMERIC(18,0);

-- Lấy dữ liệu hợp đồng
SELECT
    @KYHAN = KY_HAN,
    @LAISUAT = LAISUAT,
    @SOTIEN = SOTIEN,
    @NGAY_GN = NGAY_GIAINGAN,
    @NGAY_DH = NGAY_DAOHAN
FROM HOPDONG_TINDUNG
WHERE MA_HOPDONG_TINDUNG = @MAHDTD;

-- Gốc mỗi kỳ
SET @GOCPHAITRA_MOIKY = ROUND(@SOTIEN*1.0/@KYHAN,0);

-- Tạo kế hoạch trả nợ
WHILE @I <= @KYHAN
BEGIN

INSERT INTO KEHOACH
VALUES
(
 @MAHDTD,

 @I,

 @SOTIEN-(@I-1)*@GOCPHAITRA_MOIKY,

 @NGAY_GN,

 DATEADD(DAY,-1,DATEADD(MONTH,1,@NGAY_GN)),

 0,

 @LAISUAT,

 @GOCPHAITRA_MOIKY,

 0,

 0
);

SET @I=@I+1;
SET @NGAY_GN=DATEADD(MONTH,1,@NGAY_GN);

END
-- Điều chỉnh kỳ cuối
UPDATE KEHOACH
SET
 [Ngày cuối kỳ] = @NGAY_DH,

 [Gốc phải trả] =
 @SOTIEN -
 (
   SELECT SUM([Gốc phải trả])
   FROM KEHOACH
   WHERE [Mã HDTD]=@MAHDTD
   AND [Kỳ]<@KYHAN
 )

WHERE [Mã HDTD]=@MAHDTD
AND [Kỳ]=@KYHAN;

-- Tính số ngày
UPDATE KEHOACH
SET [Số ngày tính lãi] =
DATEDIFF(DAY,[Ngày đầu kỳ],[Ngày cuối kỳ])+1
WHERE [Mã HDTD]=@MAHDTD;

-- Tính lãi
UPDATE KEHOACH
SET [Lãi phải trả] =
ROUND([Số ngày tính lãi]*[Lãi suất trong hạn]*[Số dư đầu kỳ]/36500,0)
WHERE [Mã HDTD]=@MAHDTD;

-- Tổng tiền
UPDATE KEHOACH
SET [Tổng tiền phải trả] =
[Gốc phải trả]+[Lãi phải trả]
WHERE [Mã HDTD]=@MAHDTD;

END
GO

EXEC KEHOACH_TRANO 'CRCT-00186';

SELECT *
FROM KEHOACH
ORDER BY [Mã HDTD],[Kỳ];
